version: '2'
services:
  app:
    image: {{ cookiecutter.project_slug }}:latest
    command: ["runserver"]
    ports:
      - "8000:8000"
    volumes:
      - .:/srv/apps/{{ cookiecutter.project_slug }}/app
      - ./logs/{{ cookiecutter.project_slug }}:/srv/apps/{{ cookiecutter.project_slug }}/logs
    links:
      - postgres
    environment:
      - DB_DEFAULT_HOST=${DB_DEFAULT_HOST}
      - DB_DEFAULT_PORT=${DB_DEFAULT_PORT}
      - DB_DEFAULT_USER=${DB_DEFAULT_USER}
      - DB_DEFAULT_PASSWORD=${DB_DEFAULT_PASSWORD}
      - DB_DEFAULT_NAME=${DB_DEFAULT_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  postgres:
    image: postgres:alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_DEFAULT_USER}
      - POSTGRES_PASSWORD=${DB_DEFAULT_PASSWORD}
      - POSTGRES_DB=${DB_DEFAULT_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.data/pgdata:${PGDATA}
      - ./logs/postgresql:/var/log/postgresql
